parameters:
  displayName: ''
  workingDirectory: ''
  scheme: ''
  sdkurl: ''

jobs:
  - job: ${{ parameters.displayName }}Build
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: 'macOS-10.14'

    variables:
      - group: AgoraKeys

    steps:
      - script: cd 'iOS&macOS' && ls && python ci_macos_env.py
        env:
          AGORA_APP_ID: $(agora.appId)
          SDK_URL: ${{ parameters.sdkurl }}
      
      - script: cd '${{ parameters.workingDirectory }}' && chmod +x build_macOS.sh && ./build_macOS.sh

      - script: cd '${{ parameters.workingDirectory }}' && mkdir app && mv *.app app && mv *.xcarchive app

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: ${{ parameters.workingDirectory }}/app
          ArtifactName: ${{ parameters.displayName }}

      - template: github-release.yml
        parameters:
          displayName: ${{ parameters.displayName }}
