/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef _Included_io_agora_ex_RTCPacketProcessing
#define _Included_io_agora_ex_RTCPacketProcessing
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_io_agora_ex_RTCPacketProcessing_doRegisterProcessing
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_io_agora_ex_RTCPacketProcessing_doUnregisterProcessing
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
