/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_agora_rtc_plugin_rawdata_MediaPreProcessing */

#ifndef _Included_io_agora_rtc_plugin_rawdata_MediaPreProcessing
#define _Included_io_agora_rtc_plugin_rawdata_MediaPreProcessing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Java_io_agora_rtc_plugin_rawdata_MediaPreProcessing
 * Method:    setCallback
 */
JNIEXPORT void JNICALL Java_io_agora_rtc_plugin_rawdata_MediaPreProcessing_setCallback
  (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_io_agora_rtc_plugin_rawdata_MediaPreProcessing_setVideoCaptureByteBUffer
        (JNIEnv *, jobject, jobject);


JNIEXPORT void JNICALL Java_io_agora_rtc_plugin_rawdata_MediaPreProcessing_setAudioRecordByteBUffer
        (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_io_agora_rtc_plugin_rawdata_MediaPreProcessing_setAudioPlayByteBUffer
        (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_io_agora_rtc_plugin_rawdata_MediaPreProcessing_setBeforeAudioMixByteBUffer
        (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_io_agora_rtc_plugin_rawdata_MediaPreProcessing_setAudioMixByteBUffer
        (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL
Java_io_agora_rtc_plugin_rawdata_MediaPreProcessing_setVideoDecodeByteBUffer(JNIEnv *,
                                                                             jobject ,
                                                                             jint,
                                                                             jobject );

JNIEXPORT void JNICALL
Java_io_agora_rtc_plugin_rawdata_MediaPreProcessing_releasePoint(JNIEnv *, jobject );

#ifdef __cplusplus
}
#endif
#endif
